version: '3'
services:
  redis:
    image: "redis"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  python_flask:
    build: .
    ports:
      - "5000:5000"
    command: ["python", "-u", "/opt/project/main.py"]
    links:
      - redis
    depends_on:
      - redis
    working_dir: "/opt/project"
    volumes:
      - ~/images:/opt/project/static
      - .:/opt/project:rw
volumes:
  redis_data:
