version: '3'
services:
  redis:
    image: "redis"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  python_flask:
    build: .
    ports:
      - "5000:5000"
    command: ["tail", "-f", "/dev/null"]
    links:
      - redis
    depends_on:
      - redis
    volumes:
      - ~/images:/opt/project/static
volumes:
  redis_data:
